# DRAFT — duples/dom/duple_settings.py for the family archetype.
# Normally this file is generated by provision_duple.py's scaffold step; this is a
# hand-drafted preview of what that scaffold should look like once the "family"
# archetype exists, for the Duply team to compare against their generator.
# "dump_prompt" on CHAT below is a field added by the 2026-07-28 platform update
# (commit e7b70d3) — not present when this draft was first written.

ARCHETYPE = "family"

CHAT = {
    "gate_roles": "all",
    "dump_prompt": False,
}

REACH = {
    "enabled": False,  # unused for family — reach_custom_rules/reach_alert_log are
    "gate_roles": "creator",  # finance-shaped (ticker/threshold); this archetype uses
    "enabled_triggers": [],  # the separate SCHEDULE domain below instead.
}

MEMORY = {
    "enabled": True,
    "gate_roles": "all",
}

KNOWLEDGE = {
    "enabled": False,
    "gate_roles": "creator",
}

# NEW domain for this archetype — proactive bedtime/routine/quest-due nudges via the
# schedule.nudge agent + duples/{duple_id}/schedule/schedule_cron.py (runs daily, every
# day including weekends — unlike reach_cron.py's market-days cadence).
SCHEDULE = {
    "enabled": True,
    "gate_roles": "all",
}
