#!/usr/bin/env python3
"""Generate guide/tool-catalog.md from data/tool_catalog.yaml.

Run after editing tool_catalog.yaml:
    python scripts/gen_tool_catalog.py
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).parent.parent
CATALOG_FILE = REPO_ROOT / "data" / "tool_catalog.yaml"
OUTPUT_FILE = REPO_ROOT / "guide" / "tool-catalog.md"

PACK_HEADERS = {
    "generic":         ("generic pack", "all archetypes"),
    "finance.generic": ("finance.generic pack", "all finance archetypes"),
    "finance.set":     ("finance.set pack", "SET-market finance Duples"),
    "finance.us":      ("finance.us pack", "US-market finance Duples"),
}

PACK_ORDER = ["generic", "finance.generic", "finance.set", "finance.us"]


def format_args(args: list) -> str:
    if not args:
        return "—"
    parts = []
    for a in args:
        req = "" if a.get("required") else " *(optional)*"
        parts.append(f"`{a['name']}` ({a['type']}){req} — {a['description']}")
    return "<br>".join(parts)


def build_md(tools: list) -> str:
    by_pack: dict[str, list] = {p: [] for p in PACK_ORDER}
    for tool in tools:
        pack = tool.get("pack", "generic")
        if pack not in by_pack:
            by_pack[pack] = []
        by_pack[pack].append(tool)

    lines = [
        "# Tool Catalog",
        "",
        "> Auto-generated from `data/tool_catalog.yaml` — do not edit this file directly.",
        "> To add or update a tool: edit `data/tool_catalog.yaml` then run `python scripts/gen_tool_catalog.py`.",
        "",
    ]

    for pack in PACK_ORDER:
        pack_tools = by_pack.get(pack, [])
        if not pack_tools:
            continue

        header, audience = PACK_HEADERS.get(pack, (pack, ""))
        lines += [
            f"## {header}",
            f"*Available to: {audience}*",
            "",
            "| Tool | Description | Args |",
            "|---|---|---|",
        ]
        for tool in pack_tools:
            desc = tool.get("description", "")
            args_md = format_args(tool.get("args", []))
            lines.append(f"| `{tool['name']}` | {desc} | {args_md} |")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    if not CATALOG_FILE.exists():
        print(f"ERROR: {CATALOG_FILE} not found", file=sys.stderr)
        sys.exit(1)

    with open(CATALOG_FILE) as f:
        data = yaml.safe_load(f)

    tools = data.get("tools", [])
    if not tools:
        print("ERROR: no tools found in catalog", file=sys.stderr)
        sys.exit(1)

    md = build_md(tools)
    OUTPUT_FILE.write_text(md)
    print(f"Written {OUTPUT_FILE} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
